"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T11:45:35.157871+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, broadcast, when
from pyspark.sql.types import StringType, FloatType, DateType
import json
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.option("header", "true")
                      .option("inferSchema", "false")
                       .csv(input_path))
    
    # Add metadata columns
    transactions_df = (transactions_df.withColumn("ingestion_timestamp", lit(run_date))
                      .withColumn("source_file", lit("transactions.csv"))
                       .withColumn("pipeline_run_id", lit(run_id)))
    
    # Write as Parquet partitioned by date
    transactions_df.write.mode("overwrite").partitionBy("ingestion_timestamp").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.format("parquet")
                      .option("basePath", bronze_path)
                      .load(f"{bronze_path}/{run_date}"))
    
    # Cast columns to correct types
    transactions_df = transactions_df.withColumn("amount", col("amount").cast(FloatType()))
    transactions_df = transactions_df.withColumn("transaction_date", col("transaction_date").cast(DateType()))
    transactions_df = transactions_df.withColumn("transaction_id", col("transaction_id").cast(StringType()))
    transactions_df = transactions_df.withColumn("merchant_id", col("merchant_id").cast(StringType()))
    
    # Filter: remove records where transaction_id is NULL or amount < 0
    transactions_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))
    
    # Deduplicate: if same transaction_id appears twice, keep the record with latest ingestion_timestamp
    transactions_df = transactions_df.withColumn("rank", 
                                               when(col("ingestion_timestamp").isNotNull(), 
                                                    col("ingestion_timestamp").cast("long")).otherwise(0))
    transactions_df = transactions_df.withColumn("row_number", 
                                                ((col("transaction_id").isNotNull()) & 
                                                 (col("ingestion_timestamp").isNotNull())).cast("long"))
    transactions_df = transactions_df.withColumn("row_number", 
                                                 transactions_df.row_number().over(Window.partitionBy("transaction_id").orderBy(col("row_number").desc())))
    
    transactions_df = transactions_df.filter(col("row_number") == 1).drop("rank", "row_number")
    
    # Read merchants data and cache it
    merchants_df = (spark.read.option("header", "true")
                   .option("inferSchema", "false")
                   .csv(merchants_path))
    merchants_df = merchants_df.withColumn("merchant_id", col("merchant_id").cast(StringType()))
    merchants_df = merchants_df.cache()
    
    # Enrich: join transactions with merchants on merchant_id
    transactions_df = transactions_df.join(broadcast(merchants_df), 
                                          transactions_df.merchant_id == merchants_df.merchant_id, 
                                          "left_outer")
    
    # Add quality flag: mark records with no matching merchant as 'UNMATCHED'
    transactions_df = transactions_df.withColumn("quality_flag", 
                                                 when(col("merchant_id").isNotNull(), "CLEAN")
                                                .otherwise("UNMATCHED"))
    
    # Write as Parquet partitioned by date
    transactions_df.write.mode("overwrite").partitionBy("transaction_date").parquet(output_path)

def main():
    # Initialize SparkSession
    spark = (SparkSession.builder
            .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())
    
    # Define paths and run metadata
    input_path = "s3://sigma-datatech/raw/transactions.csv"
    merchants_path = "s3://sigma-datatech/raw/merchants.csv"
    bronze_path = "s3://sigma-datatech/bronze/transactions"
    silver_path = "s3://sigma-datatech/silver/transactions"
    run_date = "2026-05-27"
    run_id = "run_id_20260527"
    
    # Ingest Bronze layer
    ingest_bronze(spark, input_path, bronze_path, run_date, run_id)
    
    # Transform Silver layer
    transform_silver(spark, f"{bronze_path}/{run_date}", merchants_path, silver_path, run_date)
    
    # Write run metadata summary to a JSON file
    metadata = {"run_date": run_date, "run_id": run_id, "status": "COMPLETED"}
    with open(f"s3://sigma-datatech/metadata/run_metadata_{run_date}.json", "w") as f:
        json.dump(metadata, f)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, broadcast, when, coalesce, mode, lit, to_date
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType
import json

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Initialize run metadata
    run_metadata = {
        "run_date": run_date,
        "status": "SUCCESS",
        "tables": {
            "merchant_performance": None,
            "customer_ltv": None,
            "daily_summary": None
        },
        "row_counts": {}
    }

    try:
        build_merchant_performance(spark, f"{silver_path}/date={run_date}", f"{gold_output_dir}/merchant_performance", run_date)
        build_customer_ltv(spark, f"{silver_path}", f"{gold_output_dir}/customer_ltv")
        build_daily_summary(spark, f"{silver_path}/date={run_date}", f"{gold_output_dir}/daily_summary", run_date)

        # Write run metadata to JSON
        with open(f"{gold_output_dir}/run_metadata.json", "w") as f:
            json.dump(run_metadata, f)

    except Exception as e:
        run_metadata["status"] = "FAILURE"
        run_metadata["error"] = str(e)
        with open(f"{gold_output_dir}/run_metadata.json", "w") as f:
            json.dump(run_metadata, f)
        raise e

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path)

    # Filter for completed transactions
    completed_txns = silver_df.filter(col("status") == "COMPLETED")

    # Calculate metrics
    merchant_performance_df = completed_txns.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
        .agg(
            sum(col("amount")).alias("total_revenue"),
            count("*").alias("txn_count"),
            count(when(col("status") == "FAILED", 1)).alias("failed_txn_count"),
            count("*").alias("total_txn_count")
        ).withColumn("failure_rate_pct", (col("failed_txn_count") / col("total_txn_count") * 100).cast("float"))

    # Write output
    merchant_performance_df.repartition("date").write.mode("overwrite").parquet(output_path)

    # Update run metadata
    run_metadata["tables"]["merchant_performance"] = merchant_performance_df.count()
    run_metadata["row_counts"]["merchant_performance"] = merchant_performance_df.count()

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path)

    # Filter for completed transactions
    completed_txns = silver_df.filter(col("status") == "COMPLETED")

    # Calculate metrics
    customer_ltv_df = completed_txns.groupBy("customer_id") \
       .agg(
            sum(col("amount")).alias("total_spent"),
            count("*").alias("total_txns"),
            avg(col("amount")).alias("avg_txn_value"),
            min(col("transaction_date")).alias("first_txn_date"),
            max(col("transaction_date")).alias("last_txn_date"),
            mode(col("payment_method")).over(Window.partitionBy("customer_id")).alias("preferred_payment_method")
        )

    # Write output
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

    # Update run metadata
    run_metadata["tables"]["customer_ltv"] = customer_ltv_df.count()
    run_metadata["row_counts"]["customer_ltv"] = customer_ltv_df.count()

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path)

    # Calculate metrics
    daily_summary_df = silver_df.groupBy("date") \
        .agg(
            sum(when(col("status") == "COMPLETED", col("amount")).otherwise(lit(0))).alias("total_revenue"),
            count("*").alias("total_txns"),
            count(col("customer_id")).alias("unique_customers"),
            count(col("merchant_id")).alias("unique_merchants"),
            count(when(col("status") == "FAILED", 1)).alias("failed_txn_count"),
            count("*").alias("total_txn_count")
        ).withColumn("failure_rate_pct", (col("failed_txn_count") / col("total_txn_count") * 100).cast("float"))

    # Write output
    daily_summary_df.repartition("date").write.mode("overwrite").parquet(output_path)

    # Update run metadata
    run_metadata["tables"]["daily_summary"] = daily_summary_df.count()
    run_metadata["row_counts"]["daily_summary"] = daily_summary_df.count()
